`timescale 1ns/1ps
// Course lab1 port-compatible implementation. rst is active LOW; outputs
// are active HIGH in abcdefg order, with two groups of four digits.
module lab1_num_led #(parameter COUNTER_WIDTH=20)(
 input wire rst,clk,
 output wire [6:0] digital_num0,digital_num1,
 output wire [7:0] digital_cs,
 input wire [7:0] switch,input wire center_btn_key
);
 reg meta,sync,stable;
 reg [COUNTER_WIDTH-1:0] debounce;
 reg [31:0] num_led_value;
 reg [1:0] write_byte_index;
 always @(posedge clk) begin
  if(!rst)begin
   meta<=0;sync<=0;stable<=0;debounce<=0;
   num_led_value<=0;write_byte_index<=0;
  end else begin
   meta<=center_btn_key;sync<=meta;
   if(sync==stable)debounce<=0;
   else if(debounce[COUNTER_WIDTH-1])begin
    stable<=sync;debounce<=0;
    if(sync)begin
     num_led_value[8*write_byte_index+:8]<=switch;
     write_byte_index<=write_byte_index+1'b1;
    end
   end else debounce<=debounce+1'b1;
  end
 end
 lab1_hex_display #(.COUNTER_WIDTH(COUNTER_WIDTH)) display(
  .clk(clk),.rstn(rst),.value(num_led_value),
  .digital_num0(digital_num0),.digital_num1(digital_num1),.digital_cs(digital_cs));
endmodule

// Also plugs into the original num_led display placeholder region via the
// local-only overlay generated by run_course_basics.py. No teacher RTL copied.
module lab1_hex_display #(parameter COUNTER_WIDTH=20)(
 input wire clk,rstn,input wire [31:0] value,
 output wire [6:0] digital_num0,digital_num1,output wire [7:0] digital_cs
);
 reg [COUNTER_WIDTH-1:0] scan_count;
 wire [1:0] phase=scan_count[COUNTER_WIDTH-1:COUNTER_WIDTH-2];
 function [6:0] encode(input [3:0] nibble);
  begin
   case(nibble)
    4'h0:encode=7'b1111110;4'h1:encode=7'b0110000;
    4'h2:encode=7'b1101101;4'h3:encode=7'b1111001;
    4'h4:encode=7'b0110011;4'h5:encode=7'b1011011;
    4'h6:encode=7'b1011111;4'h7:encode=7'b1110000;
    4'h8:encode=7'b1111111;4'h9:encode=7'b1111011;
    4'ha:encode=7'b1110111;4'hb:encode=7'b0011111;
    4'hc:encode=7'b1001110;4'hd:encode=7'b0111101;
    4'he:encode=7'b1001111;4'hf:encode=7'b1000111;
   endcase
  end
 endfunction
 always @(posedge clk)if(!rstn)scan_count<=0;else scan_count<=scan_count+1'b1;
 // Decode selection and data from the same phase, avoiding one-cycle ghosting
 // in the original independently registered scan/segment skeleton.
 assign digital_cs=rstn ? (8'h11<<phase) : 8'b0;
 assign digital_num0=rstn ? encode(value[4*phase+:4]) : 7'b0;
 assign digital_num1=rstn ? encode(value[16+4*phase+:4]) : 7'b0;
endmodule
