# Newly transcribed from EES-338 manual/schematic; see docs/hardware.md.
set_property PACKAGE_PIN T5 [get_ports clk100]
set_property PACKAGE_PIN P15 [get_ports reset_n]
set_property PACKAGE_PIN T4 [get_ports uart_tx]
set_property PACKAGE_PIN N5 [get_ports uart_rx]
set_property PACKAGE_PIN G13 [get_ports buzzer_out]
set_property PACKAGE_PIN K2 [get_ports {led[0]}]
set_property PACKAGE_PIN J2 [get_ports {led[1]}]
set_property PACKAGE_PIN J3 [get_ports {led[2]}]
set_property PACKAGE_PIN H4 [get_ports {led[3]}]
set_property PACKAGE_PIN J4 [get_ports {led[4]}]
set_property PACKAGE_PIN G3 [get_ports {led[5]}]
set_property PACKAGE_PIN G4 [get_ports {led[6]}]
set_property PACKAGE_PIN F6 [get_ports {led[7]}]
set_property PACKAGE_PIN R1 [get_ports {switches[0]}]
set_property PACKAGE_PIN N4 [get_ports {switches[1]}]
set_property PACKAGE_PIN M4 [get_ports {switches[2]}]
set_property PACKAGE_PIN R2 [get_ports {switches[3]}]
set_property PACKAGE_PIN P2 [get_ports {switches[4]}]
set_property PACKAGE_PIN P3 [get_ports {switches[5]}]
set_property PACKAGE_PIN P4 [get_ports {switches[6]}]
set_property PACKAGE_PIN P5 [get_ports {switches[7]}]
set_property PACKAGE_PIN G2 [get_ports {digit[0]}]
set_property PACKAGE_PIN C2 [get_ports {digit[1]}]
set_property PACKAGE_PIN C1 [get_ports {digit[2]}]
set_property PACKAGE_PIN H1 [get_ports {digit[3]}]
set_property PACKAGE_PIN G1 [get_ports {digit[4]}]
set_property PACKAGE_PIN F1 [get_ports {digit[5]}]
set_property PACKAGE_PIN E1 [get_ports {digit[6]}]
set_property PACKAGE_PIN G6 [get_ports {digit[7]}]
set_property PACKAGE_PIN B4 [get_ports {segment0[0]}]
set_property PACKAGE_PIN A4 [get_ports {segment0[1]}]
set_property PACKAGE_PIN A3 [get_ports {segment0[2]}]
set_property PACKAGE_PIN B1 [get_ports {segment0[3]}]
set_property PACKAGE_PIN A1 [get_ports {segment0[4]}]
set_property PACKAGE_PIN B3 [get_ports {segment0[5]}]
set_property PACKAGE_PIN B2 [get_ports {segment0[6]}]
set_property PACKAGE_PIN D5 [get_ports {segment0[7]}]
set_property PACKAGE_PIN D4 [get_ports {segment1[0]}]
set_property PACKAGE_PIN E3 [get_ports {segment1[1]}]
set_property PACKAGE_PIN D3 [get_ports {segment1[2]}]
set_property PACKAGE_PIN F4 [get_ports {segment1[3]}]
set_property PACKAGE_PIN F3 [get_ports {segment1[4]}]
set_property PACKAGE_PIN E2 [get_ports {segment1[5]}]
set_property PACKAGE_PIN D2 [get_ports {segment1[6]}]
set_property PACKAGE_PIN H2 [get_ports {segment1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports *]
create_clock -period 10.000 -name clk100 [get_ports clk100]
create_generated_clock -name cpu_clk -source [get_ports clk100] -divide_by 10 [get_pins divided_clock_reg/Q]
# External asynchronous inputs end only at their synchronizers.
set_false_path -from [get_ports reset_n]
set_false_path -from [get_ports switches*] -to [get_pins -hier -filter {NAME =~ *switch_meta_reg*/D}]
set_false_path -from [get_ports uart_rx] -to [get_pins -hier -filter {NAME =~ *rx_meta_reg/D}]
# Human-facing outputs have no receiving clock. UART baud is verified separately.
set_output_delay -clock cpu_clk -max 10 [get_ports {led* digit* segment0* segment1* buzzer_out uart_tx}]
set_output_delay -clock cpu_clk -min 0 [get_ports {led* digit* segment0* segment1* buzzer_out uart_tx}]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
