// Optional browser smoke: PLAYWRIGHT_MODULE, PLAYWRIGHT_CHANNEL and LAB_URL override defaults.
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { PRESETS } from '../../docs/lab/engine/circuit.js';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});
const page=await browser.newPage({viewport:{width:1500,height:1100},acceptDownloads:true});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
try {
  await page.goto(new URL('playground.html',process.env.LAB_URL||'http://127.0.0.1:4173/lab/').href);
  await page.locator('[data-tab="circuit"]').click();
  const editor=page.locator('.circuit-editor'),preset=editor.locator('[data-control="preset"]');
  await preset.selectOption('nand');
  await editor.locator('.ce-node[data-node="a"]').click({position:{x:60,y:17}});
  await editor.locator('[data-property="value"]').fill('2');await page.keyboard.press('Tab');
  const inputA=editor.locator('[data-toggle="a"]');
  assert.equal(await editor.locator('.ce-node[data-node="a"] .ce-node-value').textContent(),'0');
  assert.equal(await inputA.getAttribute('aria-checked'),'false','switch reflects masked one-bit signal');
  assert.equal(await inputA.locator('span').textContent(),'0');
  await inputA.click();
  assert.equal(await editor.locator('.ce-node[data-node="a"] .ce-node-value').textContent(),'1','toggle starts from normalized zero');
  assert.equal(await inputA.getAttribute('aria-checked'),'true');
  const unknown=structuredClone(PRESETS.find(p=>p.id==='nand').netlist);
  unknown.nodes.find(n=>n.id==='a').value=null;
  await editor.locator('[data-control="file"]').setInputFiles({name:'unknown.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(unknown))});
  assert.equal(await inputA.getAttribute('role'),'checkbox','mixed state uses a compatible ARIA role');
  assert.equal(await inputA.getAttribute('aria-checked'),'mixed');
  assert.equal(await inputA.locator('span').textContent(),'X');
  await inputA.click();
  assert.equal(await editor.locator('.ce-node[data-node="a"] .ce-node-value').textContent(),'1','unknown toggle deterministically sets one');
  assert.equal(await inputA.getAttribute('role'),'switch');
  await preset.selectOption(PRESETS[0].id);
  await editor.locator('.ce-node[data-node="op"]').click({position:{x:60,y:17}});
  assert.match(await editor.locator('.ce-selection-title').innerText(),/加法器/,'mouse click selects node');
  await page.keyboard.press('Delete');
  assert.equal(await editor.locator('.ce-node').count(),3,'Delete removes a mouse-selected node');
  await preset.selectOption('challenge');
  await editor.locator('[data-add="XOR"]').click();
  const gate=editor.locator('.ce-node[data-node="g1"]');
  const before=await gate.getAttribute('transform');
  const rect=await gate.boundingBox();
  await page.mouse.move(rect.x+70,rect.y+15);await page.mouse.down();await page.mouse.move(rect.x+170,rect.y+60,{steps:8});await page.mouse.up();
  assert.notEqual(await gate.getAttribute('transform'),before,'drag must move node');
  async function port(id,p,direction) {await editor.locator(`.ce-port[data-node="${id}"][data-port="${p}"][data-direction="${direction}"]`).click();}
  await port('a','out','out');await port('g1','a','in');
  await port('b','out','out');await port('g1','b','in');
  await port('g1','out','out');await port('y','in','in');
  assert.equal(await editor.locator('.ce-wire').count(),3);
  await editor.locator('[data-action="challenge"]').click();
  assert.match(await editor.locator('.ce-challenge-result').innerText(),/4 \/ 4/);
  await editor.locator('[data-toggle="a"]').click();
  assert.match(await editor.locator('.ce-node[data-node="y"] .ce-node-value').textContent(),/^1$/);
  // Keyboard selection/deletion exercises the accessible wire controls.
  await editor.locator('.ce-wire[data-wire="0"]').focus();await page.keyboard.press('Enter');await page.keyboard.press('Delete');
  assert.equal(await editor.locator('.ce-wire').count(),2);
  assert.match(await editor.locator('.ce-node[data-node="y"] .ce-node-value').textContent(),/未知/);
  await preset.selectOption('fulladder');await editor.locator('[data-control="challenge"]').selectOption('fulladder');await editor.locator('[data-action="challenge"]').click();
  assert.match(await editor.locator('.ce-challenge-result').innerText(),/8 \/ 8/);
  await preset.selectOption('dff');
  assert.equal(await editor.locator('.ce-node[data-node="y"] .ce-node-value').textContent(),'0');
  await editor.locator('[data-action="clock"]').click();
  assert.equal(await editor.locator('.ce-node[data-node="y"] .ce-node-value').textContent(),'1');
  await editor.locator('[data-action="clock"]').click();
  assert.equal(await editor.locator('.ce-node[data-node="y"] .ce-node-value').textContent(),'0');
  const invalid=Buffer.from(JSON.stringify({nodes:[{id:'bad',type:'NOT',width:33,x:0,y:0}],wires:[]}));
  await editor.locator('[data-control="file"]').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:invalid});
  assert.match(await editor.locator('.ce-status').innerText(),/导入失败/);
  assert.equal(await editor.locator('.ce-node').count(),3,'invalid import preserves current netlist');
  const xor=PRESETS.find(p=>p.id==='xor32').netlist;
  await editor.locator('[data-control="file"]').setInputFiles({name:'xor.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(xor))});
  assert.equal(await editor.locator('.ce-node[data-node="y"] .ce-node-value').textContent(),'0x00000002');
  const downloadPromise=page.waitForEvent('download');await editor.locator('[data-action="export"]').click();const download=await downloadPromise;
  const stream=await download.createReadStream(),chunks=[];for await(const chunk of stream) chunks.push(chunk);
  assert.deepEqual(JSON.parse(Buffer.concat(chunks).toString()),xor,'export preserves imported graph');
  await editor.locator('[data-action="install"]').click();
  for(let i=0;i<30;i++) {if(await page.locator('#status').innerText()==='已完成') break;await page.locator('#step').click();}
  assert.equal(await page.locator('[data-register="9"] .reg-value').innerText(),'00000002','installed XOR must affect CPU register');
  await page.locator('[data-state="memory"]').click();
  assert.equal(await page.locator('[data-address="0"] .reg-value').innerText(),'00000002','installed XOR must reach RAM');
  await page.locator('[data-tab="circuit"]').click();await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'mobile document must not overflow horizontally');
  assert.deepEqual(errors,[]);
  console.log('Circuit browser: drag, three wires, challenge tables, switch, delete, DFF clock, malformed/valid import, export, installed XOR CPU/RAM, mobile layout passed.');
} finally {await browser.close();}
